---
title: "R-101"
subtitle: "R installation instructions"
author: ""
date: ""
output: pdf_document
---

There are two things you need to get started with R. These are:

## R

1. Download R directly from CRAN [here](https://cran.rstudio.com/) (CRAN is the "Comprehensive R Archive Network").
2. Choose your operating system and download the most up-to-date version that is available. As of 2016-05-15 that's 3.3.0.
3. Install R on your system. If you're running a modern computer (less than 5 years old) you're probably safe to install the 64-bit version. If you have a very old laptop, it's probably best to install the 32-bit version. (Note that 32/64-bit is an option in the installer once you launch it).

## R-Studio

1. Download RStudio from the website [here](https://www.rstudio.com/products/rstudio/download/).
2. Install RStudio on to your machine. It should automatically detect your R installation and set itself up accordingly. 


You're done. RStudio have a nice overview of the environment in the first ~10 minutes of [this video](https://www.rstudio.com/resources/webinars/rstudio-essentials-webinar-series-part-1/), but we'll go through it in the sessions, too.

